/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as IntegritetRouteImport } from './routes/integritet'
import { Route as OmRouteImport } from './routes/om'
import { Route as PriserRouteImport } from './routes/priser'
import { Route as SupportRouteImport } from './routes/support'
import { Route as TackRouteImport } from './routes/tack'
import { Route as VillkorRouteImport } from './routes/villkor'
import { Route as DokumentIndexRouteImport } from './routes/dokument/index'
import { Route as DokumentSlugRouteImport } from './routes/dokument/$slug'
import { Route as GuiderIndexRouteImport } from './routes/guider/index'
import { Route as GuiderSlugRouteImport } from './routes/guider/$slug'
import { Route as ApiStripeWebhookRouteImport } from './routes/api/stripe.webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegritetRoute = IntegritetRouteImport.update({
  id: '/integritet',
  path: '/integritet',
  getParentRoute: () => rootRouteImport,
} as any)
const OmRoute = OmRouteImport.update({
  id: '/om',
  path: '/om',
  getParentRoute: () => rootRouteImport,
} as any)
const PriserRoute = PriserRouteImport.update({
  id: '/priser',
  path: '/priser',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const TackRoute = TackRouteImport.update({
  id: '/tack',
  path: '/tack',
  getParentRoute: () => rootRouteImport,
} as any)
const VillkorRoute = VillkorRouteImport.update({
  id: '/villkor',
  path: '/villkor',
  getParentRoute: () => rootRouteImport,
} as any)
const DokumentIndexRoute = DokumentIndexRouteImport.update({
  id: '/dokument/',
  path: '/dokument/',
  getParentRoute: () => rootRouteImport,
} as any)
const DokumentSlugRoute = DokumentSlugRouteImport.update({
  id: '/dokument/$slug',
  path: '/dokument/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const GuiderIndexRoute = GuiderIndexRouteImport.update({
  id: '/guider/',
  path: '/guider/',
  getParentRoute: () => rootRouteImport,
} as any)
const GuiderSlugRoute = GuiderSlugRouteImport.update({
  id: '/guider/$slug',
  path: '/guider/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStripeWebhookRoute = ApiStripeWebhookRouteImport.update({
  id: '/api/stripe/webhook',
  path: '/api/stripe/webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/integritet': typeof IntegritetRoute
  '/om': typeof OmRoute
  '/priser': typeof PriserRoute
  '/support': typeof SupportRoute
  '/tack': typeof TackRoute
  '/villkor': typeof VillkorRoute
  '/dokument/$slug': typeof DokumentSlugRoute
  '/guider/$slug': typeof GuiderSlugRoute
  '/dokument/': typeof DokumentIndexRoute
  '/guider/': typeof GuiderIndexRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/integritet': typeof IntegritetRoute
  '/om': typeof OmRoute
  '/priser': typeof PriserRoute
  '/support': typeof SupportRoute
  '/tack': typeof TackRoute
  '/villkor': typeof VillkorRoute
  '/dokument/$slug': typeof DokumentSlugRoute
  '/guider/$slug': typeof GuiderSlugRoute
  '/dokument': typeof DokumentIndexRoute
  '/guider': typeof GuiderIndexRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/integritet': typeof IntegritetRoute
  '/om': typeof OmRoute
  '/priser': typeof PriserRoute
  '/support': typeof SupportRoute
  '/tack': typeof TackRoute
  '/villkor': typeof VillkorRoute
  '/dokument/$slug': typeof DokumentSlugRoute
  '/guider/$slug': typeof GuiderSlugRoute
  '/dokument/': typeof DokumentIndexRoute
  '/guider/': typeof GuiderIndexRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/integritet'
    | '/om'
    | '/priser'
    | '/support'
    | '/tack'
    | '/villkor'
    | '/dokument/$slug'
    | '/guider/$slug'
    | '/dokument/'
    | '/guider/'
    | '/api/stripe/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/integritet'
    | '/om'
    | '/priser'
    | '/support'
    | '/tack'
    | '/villkor'
    | '/dokument/$slug'
    | '/guider/$slug'
    | '/dokument'
    | '/guider'
    | '/api/stripe/webhook'
  id:
    | '__root__'
    | '/'
    | '/integritet'
    | '/om'
    | '/priser'
    | '/support'
    | '/tack'
    | '/villkor'
    | '/dokument/$slug'
    | '/guider/$slug'
    | '/dokument/'
    | '/guider/'
    | '/api/stripe/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  IntegritetRoute: typeof IntegritetRoute
  OmRoute: typeof OmRoute
  PriserRoute: typeof PriserRoute
  SupportRoute: typeof SupportRoute
  TackRoute: typeof TackRoute
  VillkorRoute: typeof VillkorRoute
  DokumentSlugRoute: typeof DokumentSlugRoute
  GuiderSlugRoute: typeof GuiderSlugRoute
  DokumentIndexRoute: typeof DokumentIndexRoute
  GuiderIndexRoute: typeof GuiderIndexRoute
  ApiStripeWebhookRoute: typeof ApiStripeWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integritet': {
      id: '/integritet'
      path: '/integritet'
      fullPath: '/integritet'
      preLoaderRoute: typeof IntegritetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/om': {
      id: '/om'
      path: '/om'
      fullPath: '/om'
      preLoaderRoute: typeof OmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/priser': {
      id: '/priser'
      path: '/priser'
      fullPath: '/priser'
      preLoaderRoute: typeof PriserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tack': {
      id: '/tack'
      path: '/tack'
      fullPath: '/tack'
      preLoaderRoute: typeof TackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/villkor': {
      id: '/villkor'
      path: '/villkor'
      fullPath: '/villkor'
      preLoaderRoute: typeof VillkorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dokument/': {
      id: '/dokument/'
      path: '/dokument'
      fullPath: '/dokument/'
      preLoaderRoute: typeof DokumentIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dokument/$slug': {
      id: '/dokument/$slug'
      path: '/dokument/$slug'
      fullPath: '/dokument/$slug'
      preLoaderRoute: typeof DokumentSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guider/': {
      id: '/guider/'
      path: '/guider'
      fullPath: '/guider/'
      preLoaderRoute: typeof GuiderIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guider/$slug': {
      id: '/guider/$slug'
      path: '/guider/$slug'
      fullPath: '/guider/$slug'
      preLoaderRoute: typeof GuiderSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stripe/webhook': {
      id: '/api/stripe/webhook'
      path: '/api/stripe/webhook'
      fullPath: '/api/stripe/webhook'
      preLoaderRoute: typeof ApiStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  IntegritetRoute: IntegritetRoute,
  OmRoute: OmRoute,
  PriserRoute: PriserRoute,
  SupportRoute: SupportRoute,
  TackRoute: TackRoute,
  VillkorRoute: VillkorRoute,
  DokumentSlugRoute: DokumentSlugRoute,
  GuiderSlugRoute: GuiderSlugRoute,
  DokumentIndexRoute: DokumentIndexRoute,
  GuiderIndexRoute: GuiderIndexRoute,
  ApiStripeWebhookRoute: ApiStripeWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
